### ISSUE TITLE
Major refactor of the Matchmaker & Planner Module.

### ISSUE THREAD

**Issue by adriannieto** [SeaCloudsEU/SeaCloudsPlatform#12]
The current codebase of the Matchmaker & Planner Module doesn't follow Object-Oriented Programming guidelines. Must be rewritten from scratch.

**Comment by andreaturli** [comment]
What's the status of this issue? Is it still valid after 5 months?

**Comment by perezp** [comment]
Overall, I think it can be closed, not because the issue has been solved, but due to the change in the context since the issue was created. 

What changes in the context: 
- Now some parts of the planner are being redesigned/reimplemented (e.g., Matchmaker). The redesign should also cover the implementation issue.
- Now the planner module contains the code of the optimizer while in the date of the issue did not. 

Why not solved the issue:
- Code in classes to which the issue refers is still the same.

**Comment by szenzaro** [comment]
Mathcmaker and Planner have been refactored and will be refactored again once we complete di upper layer. I think we can close the issue for now.
